name: Deploy to Google Artifact Registry

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bump2version

    - name: Configure Git
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
    - name: Determine version bump
      id: version_bump
      run: |
        if [[ "${{ github.event.release.tag_name }}" == *"-major"* ]]; then
          echo "::set-output name=part::major"
        elif [[ "${{ github.event.release.tag_name }}" == *"-minor"* ]]; then
          echo "::set-output name=part::minor"
        else
          echo "::set-output name=part::patch"
        fi

    - name: Bump version and create tag
      if: github.event_name == 'release'
      run: |
        bump2version ${{ steps.version_bump.outputs.part }} --commit --tag
        git push --follow-tags


    # - name: Determine version bump
    #   id: version_bump
    #   run: |
    #     if [[ "${{ github.event.release.tag_name }}" == *"-major"* ]]; then
    #       echo "PART=major" >> $GITHUB_ENV
    #     elif [[ "${{ github.event.release.tag_name }}" == *"-minor"* ]]; then
    #       echo "PART=minor" >> $GITHUB_ENV
    #     else
    #       echo "PART=patch" >> $GITHUB_ENV
    #     fi

    # - name: Bump version and create tag
    #   if: github.event_name == 'release'
    #   run: |
    #     bump2version $PART --commit --tag
    #     git push --follow-tags


    - name: Build and publish to Google Artifact Registry
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        TWINE_USERNAME: oauth2accesstoken
      run: |
        echo "${GCP_SA_KEY}" > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        export TWINE_PASSWORD=$(gcloud auth print-access-token)
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://us-python.pkg.dev/celes-platform-dev/celes-cloud/ dist/*
        rm gcp-key.json
